[features]
seeds = false
skip-lint = false
[programs.localnet]
madmints = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
transferSol = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/transferSol.ts"
transferSolUsingNonce = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/transferSolUsingNonce.ts"
mintNft = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/mintNft.ts"
mintNftUsingNonce = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/mintNftUsingNonce.ts"
10kMintNfts = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/10kMintNfts.ts"
10kMintNftsUsingNonce = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/10kMintNftsUsingNonce.ts"

# Set source RPC for clone
[test.validator]
url = "https://api.devnet.solana.com"
[test]
startup_wait = 20000

# Clone Metaplex program from Devnet
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"